version: '3.8'

networks:
  hanse-laravel-network:
    driver: bridge
    external: true

services:
  mariadb-hanse:
    image: bitnami/mariadb:latest
    networks:
      - hanse-laravel-network
    volumes:
      - ./db:/bitnami/mariadb
    environment:
      MARIADB_ROOT_PASSWORD: rootpass
      MARIADB_DATABASE: hanse_db
      MARIADB_USER: db_hanse_user
      MARIADB_PASSWORD: rootpass
    ports:
      - "3307:3306"

  laravel-api:
    build:
      context: ./api
    networks:
      - hanse-laravel-network
    ports:
      - "8084:8080"
    environment:
      DB_HOST: mariadb-hanse
      DB_PORT: 3306
      DB_USERNAME: root
      DB_DATABASE: hanse_db
    depends_on:
      - mariadb-hanse
    command: php artisan serve --host=0.0.0.0 --port=8080

  vue-frontend:
    build:
      context: ./frontend
    networks:
      - hanse-laravel-network
    ports:
      - "8085:80"