name: Deploy to VPS named

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Debug secrets (remove this after debugging)
        run: |
          echo "SERVER_IP='${{ secrets.SERVER_IP }}'"
          echo "SERVER_USER='${{ secrets.SERVER_USER }}'"

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: "${{ secrets.SERVER_IP }}"
          username: "${{ secrets.SERVER_USER }}"
          key: "${{ secrets.SERVER_SSH_KEY }}"
          script: |
            ls
            cd /root/hansecom
            ls
            git pull origin main
            docker compose down || true
            docker compose build
            docker compose up -d
            docker compose exec laravel-api php artisan migrate --force
